CCFLAGS=-W -Wall -Werror

prog : zpixel.o pile.o main.o
	gcc zpixel.o pile.o main.o -o prog

zpixel.o: zpixel.h zpixel.c
	gcc $(CCFLAGS) -c zpixel.c -o zpixel.o

pile.o : pile.h pile.c
	gcc $(CCFLAGS) -c pile.c -o pile.o

main.o : main.c pile.h
	gcc $(CCFLAGS) -c main.c -o main.o

clean :
	rm -rf *.o prog
